# Generated by Django 4.2.16 on 2025-01-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='type',
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='private', max_length=30),
        ),
        migrations.AlterField(
            model_name='channelmembership',
            name='role',
            field=models.CharField(choices=[('member', 'member'), ('admin', 'admin')], default='member', max_length=20),
        ),
    ]
