# Generated by Django 4.2.16 on 2025-01-23 07:24

import channel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_remove_channel_type_channel_channel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('public', 'PUBLIC'), ('private', 'PRIVATE')], default=channel.models.ChannelType['PRIVATE'], max_length=30),
        ),
        migrations.AlterField(
            model_name='channelmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('member', 'MEMBER')], default=channel.models.ChannelMembershipType['MEMBER'], max_length=20),
        ),
    ]
