# Generated by Django 4.2.16 on 2025-01-23 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_alter_channel_channel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='channel_type',
            new_name='type',
        ),
    ]
