# Generated by Django 4.2.16 on 2025-01-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_rename_channel_type_channel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='type',
            field=models.CharField(choices=[('public', 'PUBLIC'), ('private', 'PRIVATE')], default='public', max_length=30),
        ),
    ]
