# Generated by Django 4.2.16 on 2025-01-23 09:20

import channel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_alter_channel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('member', 'MEMBER')], default=channel.models.ChannelMembershipType['MEMBER'], max_length=200),
        ),
    ]
