# Generated by Django 4.2.16 on 2025-01-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0008_alter_channel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelmessage',
            old_name='sender',
            new_name='user',
        ),
    ]
