# Generated by Django 4.2.16 on 2025-01-25 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0009_rename_sender_channelmessage_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelmessage',
            old_name='user',
            new_name='sender',
        ),
    ]
