# Generated by Django 4.2.16 on 2025-01-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0010_rename_user_channelmessage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('member', 'MEMBER')], default='member', max_length=200),
        ),
    ]
