# Generated by Django 4.2.16 on 2025-01-25 20:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0011_alter_channelmembership_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channelmembership',
            unique_together={('user', 'channel')},
        ),
    ]
