# Generated by Django 4.2.16 on 2025-01-25 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0013_remove_channel_type_channel_channel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmembership',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_membership', to='channel.channel'),
        ),
        migrations.AlterField(
            model_name='channelmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
