# Generated by Django 4.2.16 on 2025-01-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0015_alter_channelmembership_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
