# Generated by Django 4.2.16 on 2025-01-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0016_alter_channel_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelmessage',
            old_name='image',
            new_name='media',
        ),
    ]
