# Generated by Django 4.2.16 on 2024-12-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_options_user_created_at_user_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birth_data',
            new_name='birth_date',
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
