# Generated by Django 4.2.16 on 2024-12-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_deviceinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
