# Generated by Django 4.2.16 on 2025-01-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_deviceinfo_options_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
