# Generated by Django 4.2.16 on 2025-01-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermission',
            name='can_send_media',
            field=models.BooleanField(default=True),
        ),
    ]
