# Generated by Django 4.2.16 on 2025-01-22 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_grouppermission_can_send_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created_at'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='groupparticipant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='grouppermission',
            options={},
        ),
    ]
