# Generated by Django 4.2.16 on 2025-01-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_liked_by_message_liked_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='scheduledmessage',
            options={'verbose_name': 'Schedule Message', 'verbose_name_plural': 'Schedule Messages'},
        ),
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
        migrations.AlterModelTable(
            name='scheduledmessage',
            table='schedule_message',
        ),
    ]
